name: CI

on:
  push:
    branches: [ "main", "homolog" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Instalar dependências
        run: npm install
